name: Waka Readme

on:
  schedule:
    # Runs at 12am EST
    - cron: '0 5 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: true
          SHOW_OS: false
          SHOW_TIMEZONE: false
          SHOW_LOC_CHART: false
          SHOW_SHORT_INFO: false
          SHOW_EDITORS: false
          SHOW_PROJECTS: false
          SHOW_PROFILE_VIEWS: false


